server:
  port: 8080
spring:
  application:
    name: mlb-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
      config:
        server-addr: ${NACOS_SERVER}
        extension-configs:
          - data-id: gateway-dev.yaml
            refresh: true
